GET http://localhost:3000/products

### 
POST http://localhost:3000/products
Content-Type: application/json

{
  "code": "sdasd",
  "description": "asdasd",
  "unit": "UN",
  "price": 20.00,
  "situation": "new"
}
###
GET http://localhost:3000/products/3

###
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "code": "sdasd",
  "description": "asdasd",
  "unit": "UN",
  "price": 20.00,
  "situation": "new"

}

###
DELETE http://localhost:3000/products/3