GET http://localhost:3000/products/
###
GET http://localhost:3000/products/4cddbfa7-5c21-4a4c-b92f-9b71aa581b4f
###
GET http://localhost:3000/products/save-product
###
GET http://localhost:3000/products/parent

###
DELETE http://localhost:3000/products/444
### 
POST http://localhost:3000/products
Content-Type: application/json

{
  "code": "Test",
  "description": "asdasd",
  "unit": "UN",
  "price": 20.00,
  "situation": "new"
  
}
###
GET http://localhost:3000/products/444
###
GET http://localhost:3000/products/CHUTFMC/children
###
GET http://localhost:3000/products/CHUTFMC/parentandchildren


###
PATCH http://localhost:3000/products/5256c434-dca7-4fb5-838f-73deac94747c
Content-Type: application/json

{
  "code": "sdasd",
  "description": "asdasd",
  "unit": "UN",
  "price": 20.00,
  "situation": "new",
  "externalImageURLs": ["asdasd"]

}

###
GET http://localhost:3000/products/5256c434-dca7-4fb5-838f-73deac94747c



###
POST http://localhost:3000/products/import
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZgW

------WebKitFormBoundary7MA4YWxkTrZgW
Content-Disposition: form-data; name="file"; filename="products.csv"
Content-Type: text/csv

id,code,description,unit,price,situation
1,sdasd,asdasd,UN,20.00,new
221,sdasd,asdasd,UN,20.00,new
------WebKitFormBoundary7MA4YWxkTrZgW--



# curl -X POST http://localhost:3000/products/import \
#   -H "Content-Type: multipart/form-data" \
#   -F "file=@products.csv"



